# Generated by Django 2.2.1 on 2019-06-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
