# Generated by Django 2.2.1 on 2019-06-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empire', '0004_auto_20190602_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('username', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
