# Generated by Django 2.2.1 on 2019-06-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empire', '0005_auto_20190602_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBackDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('customer_mail', models.EmailField(max_length=100)),
                ('customer_phone', models.TextField(blank=True, max_length=20)),
                ('subject', models.TextField(blank=True, max_length=250)),
                ('message', models.TextField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ShopDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.TextField(max_length=300)),
                ('addess1', models.TextField(max_length=250)),
                ('addess2', models.TextField(blank=True, max_length=250)),
                ('phone_number1', models.TextField(blank=True, max_length=200)),
                ('phone_number2', models.TextField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=50)),
                ('timing', models.TextField(max_length=150)),
                ('facebook_link', models.TextField(max_length=150)),
                ('twitter_link', models.TextField(max_length=150)),
                ('shop_name', models.TextField(max_length=150)),
                ('address1_latitude', models.TextField(blank=True, max_length=50)),
                ('address1_longitude', models.TextField(blank=True, max_length=50)),
                ('address2_latitude', models.TextField(blank=True, max_length=50)),
                ('address2_longitude', models.TextField(blank=True, max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
