# Generated by Django 2.2.1 on 2019-06-02 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empire', '0006_auto_20190602_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopdetails',
            old_name='addess1',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='shopdetails',
            old_name='addess2',
            new_name='address2',
        ),
    ]
