# Generated by Django 2.2.1 on 2019-06-10 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empire', '0007_auto_20190602_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopdetails',
            options={'verbose_name': 'ShopDetail', 'verbose_name_plural': 'ShopDetails'},
        ),
    ]
