# Generated by Django 2.2.1 on 2019-06-10 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empire', '0008_auto_20190610_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackdetails',
            options={'verbose_name': 'feedback', 'verbose_name_plural': 'listOfFeedback'},
        ),
        migrations.AlterModelOptions(
            name='userlogin',
            options={'verbose_name': 'userLogin', 'verbose_name_plural': 'usersLogin'},
        ),
    ]
